version: '3'
services:
  terraria-tshock:
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: terraria_tshock_server
    working_dir: /server
    volumes:
      - ./world:/server/world
    ports:
      - '7777:7777'
    tty: true
    