version: '3'
services:
  terraria:
    build:
      dockerfile: docker/vanilla/Dockerfile
      context: .
    container_name: terraria_server
    working_dir: /server
    volumes:
      - ./tshock/world:/server/world
    ports:
      - '7777:7777'
    tty: true
